"use client";
import { useEffect, useState } from "react";
import { Anchor, Badge, Button, Card, Group, Loader, Modal, Pagination, SegmentedControl, Select, Stack, Table, Text, Textarea } from "@mantine/core";
import { notifications } from "@mantine/notifications";
import { refreshAdminNotifications } from "@/lib/teacher-approvals";
import { useAuthStore } from "@/store/auth";
import { ReimbursementRequestForm } from "./ReimbursementRequestForm";
import { PageHeader } from "@/components/ui/admin";
import { getReimbursements, reviewReimbursement } from "../api";
import type { Reimbursement, ReimbursementList } from "../types";
const money = (n: number) => new Intl.NumberFormat("id-ID", { style:"currency", currency:"IDR", maximumFractionDigits:0 }).format(n);
export default function ReimbursementsContent() {
 const session=useAuthStore(state=>state.session);
 const canReview=Boolean(session?.roles.includes("superadmin"));
 const [scope,setScope]=useState<"all"|"mine">("all");
 const [data,setData] = useState<ReimbursementList | null>(null), [page,setPage] = useState(1), [status,setStatus] = useState<string | null>("pending"), [reload,setReload] = useState(0);
 const [loading,setLoading] = useState(true), [error,setError] = useState(""), [selected,setSelected] = useState<Reimbursement | null>(null), [note,setNote] = useState(""), [busy,setBusy] = useState(false);
 useEffect(() => { let active=true; getReimbursements(page,status || "",scope).then(d => {if(active){setData(d);setError("");}}).catch(e => {if(active)setError(e.message);}).finally(() => {if(active)setLoading(false);}); return () => {active=false;}; },[page,status,scope,reload]);
 async function review(approve: boolean) { if(!selected||!canReview)return; setBusy(true); try {await reviewReimbursement(selected.id,approve,note);refreshAdminNotifications();setSelected(null);setLoading(true);setReload(n => n+1);notifications.show({color:"green",message:approve ? "Disetujui dan dicatat sebagai reimbursement finance." : "Pengajuan ditolak."});} catch(e){notifications.show({color:"red",message:e instanceof Error ? e.message : "Gagal review."});} finally {setBusy(false);} }
 return <Stack><PageHeader eyebrow="Finance" title="Reimbursement" description={canReview ? "Review pengajuan guru dan admin. Hanya superadmin yang dapat menyetujui atau menolak pengajuan." : "Lihat seluruh pengajuan atau pengajuan Anda sendiri. Persetujuan dan penolakan hanya dapat dilakukan oleh superadmin."} /><ReimbursementRequestForm onSubmitted={()=>{setScope("mine");setStatus("pending");setLoading(true);setPage(1);setReload(n=>n+1);refreshAdminNotifications();}} /><Group justify="space-between"><SegmentedControl aria-label="Daftar pengajuan reimbursement" value={scope} onChange={value=>{setScope(value as "all"|"mine");setPage(1);setLoading(true);}} data={[{value:"all",label:"Semua pengajuan"},{value:"mine",label:"Pengajuan saya"}]} /><Select label="Status pengajuan" maw={300} data={[{value:"pending",label:"Menunggu review"},{value:"approved",label:"Disetujui"},{value:"rejected",label:"Ditolak"}]} clearable placeholder="Semua status" value={status} onChange={v => {setStatus(v);setPage(1);setLoading(true);}} /></Group>
 {error && <Card withBorder><Text c="red" role="alert">{error}</Text><Button mt="sm" onClick={() => {setLoading(true);setReload(n=>n+1);}}>Coba lagi</Button></Card>}
 {loading ? <Loader /> : !error && data && <Card withBorder p="lg"><Table.ScrollContainer minWidth={700}><Table highlightOnHover><Table.Thead><Table.Tr><Table.Th>Pemohon / Keperluan</Table.Th><Table.Th>Tanggal pembelian</Table.Th><Table.Th>Nominal</Table.Th><Table.Th>Status</Table.Th><Table.Th /></Table.Tr></Table.Thead><Table.Tbody>{data.items.map(item => <Table.Tr key={item.id}><Table.Td><Text fw={600}>{item.requester?.full_name ?? item.staff_members?.full_name}</Text><Text size="xs" c="dimmed">{item.requester?.email ?? item.staff_members?.email}</Text><Text size="sm">{item.title} · {item.category}</Text></Table.Td><Table.Td>{item.purchase_date}</Table.Td><Table.Td>{money(item.amount)}</Table.Td><Table.Td><Badge color={item.status === "approved" ? "teal" : item.status === "rejected" ? "red" : "yellow"}>{item.status}</Badge></Table.Td><Table.Td><Button size="xs" variant="light" onClick={() => {setSelected(item);setNote("");}}>{canReview ? "Detail & review" : "Detail"}</Button></Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer>{!data.items.length && <Text p="lg" c="dimmed">Tidak ada pengajuan.</Text>}{data.total > 10 && <Pagination mt="lg" total={Math.ceil(data.total/10)} value={page} onChange={v => {setPage(v);setLoading(true);}} />}</Card>}
 <Modal opened={!!selected} onClose={() => {if(!busy)setSelected(null);}} closeOnEscape={!busy} closeOnClickOutside={!busy} withCloseButton={!busy} title="Detail reimbursement" centered size="lg">{selected && <Stack><Text fw={600}>{selected.requester?.full_name ?? selected.staff_members?.full_name} · {money(selected.amount)}</Text><Text fw={600}>{selected.title} · {selected.category}</Text><Text>Tanggal pembelian: {selected.purchase_date}</Text>{selected.purchase_url && <Anchor href={selected.purchase_url} target="_blank" rel="noopener noreferrer">{selected.purchase_url}</Anchor>}{selected.evidence_url ? <Anchor href={selected.evidence_url} target="_blank" rel="noopener noreferrer">Lihat bukti pembelian</Anchor> : <Text c="red">Bukti belum dapat dibuka. Muat ulang daftar dan coba lagi.</Text>}{selected.notes && <Text>Catatan pemohon: {selected.notes}</Text>}{selected.review_note && <Text>Catatan review: {selected.review_note}</Text>}{selected.expense_id && <Text size="sm">Expense #{selected.expense_id} · {selected.finance_expenses?.status === "done" ? "Dibayar" : "Menunggu pembayaran"}</Text>}{canReview && selected.status === "pending" && <><Textarea label="Catatan review" description="Wajib diisi jika menolak pengajuan." value={note} maxLength={2000} disabled={busy} onChange={e => setNote(e.currentTarget.value)} /><Group justify="flex-end"><Button variant="default" disabled={busy} onClick={() => setSelected(null)}>Batal</Button><Button color="red" disabled={busy || !note.trim()} onClick={() => void review(false)}>Tolak</Button><Button loading={busy} disabled={!selected.evidence_url} onClick={() => void review(true)}>Setujui</Button></Group></>}</Stack>}</Modal>
 </Stack>;
}
