export type ExtractionStatus = "queued" | "processing" | "completed" | "completed_with_errors" | "failed" | "cancelled";
export type ExtractionFile = { id: string; file_name: string; relative_path: string; folder_path?: string | null;
  status: string; stage: string; question_codes: string[]; question_count: number; aligned_count: number;
  review_count: number; failed_count: number; error_message?: string | null; created_at: string;
  updated_at: string; completed_at?: string | null; source_deleted_at?: string | null };
export type ExtractionJob = { id: string; subject: string; status: ExtractionStatus; stage: string; total_files: number;
  processed_files: number; total_questions: number; aligned_questions: number; failed_questions: number;
  current_file?: string | null; error_message?: string | null; created_at: string; finished_at?: string | null;
  job_type?: "file_extraction" | "question_reprocess"; selected_question_ids?: string[];
  question_extraction_files?: ExtractionFile[] };
export type QuestionContent = { question?: string | Record<string, string>; answer?: Record<string, string>; choices?: Record<string, string> };
export type VocabEntry = { pinyin?: string; en: string; en_phrase?: string };
export type Vocab = Record<string, VocabEntry>;
export type EnVocabEntry = { zh: string; pinyin?: string };
export type ExplanationAlignment = { vocab_zh?: Vocab; vocab_en?: Record<string, EnVocabEntry> };
export type QuestionAlignment = { vocab?: Vocab; explanation?: ExplanationAlignment };
export type QuestionSummary = { id: string; code: string; difficulty: string; status: string; question_type: string;
  content_en: QuestionContent; content_zh: QuestionContent; image_url?: string | null; created_at: string };
export type QuestionDetail = QuestionSummary & { answer: string; explanation_en: string; explanation_zh: string;
  alignment?: QuestionAlignment; extraction_job_id: string; topics?: { code: string; name: string; subjects?: { code: string; name: string } } };
export type PageResult<T> = { items: T[]; total: number; page: number; page_size: number };
export type ExtractorReadiness = { ready: boolean; ocr_provider: string; missing: string[] };
export type ProviderName = "anthropic" | "deepseek" | "kimi";
export type ProviderKeyStatus = { use_default: boolean; personal_key_configured: boolean; default_key_configured: boolean };
export type ProviderSettings = { providers: Record<ProviderName, ProviderKeyStatus> };
export type ProviderKeyUpdate = { use_default: boolean; api_key?: string; clear_personal_key?: boolean };
