"use client";

import { useMemo, useState } from "react";
import { ActionIcon, Badge, Box, Button, Card, Divider, Drawer, FileInput, Group, Menu, Modal, NumberInput, ScrollArea, Select, SimpleGrid, Stack, Table, Text, Textarea, TextInput, UnstyledButton } from "@mantine/core";
import { DatePickerInput, DateTimePicker } from "@mantine/dates";
import { notifications } from "@mantine/notifications";
import { IconBuildingBank, IconCheck, IconChevronDown, IconDotsVertical, IconDownload, IconEdit, IconExternalLink, IconPlus, IconReceipt, IconTrash, IconUpload, IconWallet } from "@tabler/icons-react";
import { DetailItem, MetricCard, PageHeader } from "@/components/ui/admin";
import { formatCurrency, formatDate } from "@/lib/format";
import { useAdminStore } from "@/store/admin";
import type { Expense } from "@/types/admin";
import { exportCsv } from "../utils";

const blankExpense = (): Expense => ({ id: 0, reference: `EXP-${new Date().toISOString().slice(0, 10).replaceAll("-", "")}`, category: "Maintenance", customCategory: "", date: new Date().toISOString().slice(0, 16), paidBy: "", evidenceUrl: "", amount: 0, status: "Pending", notes: "", recurring: false });
const STATUS_OPTIONS: Expense["status"][] = ["Pending", "Done"];
const expenseCategoryLabel = (item: Pick<Expense, "category" | "customCategory">) => item.category === "Lainnya" ? item.customCategory?.trim() || "Lainnya" : item.category;
const toPickerValue = (value: string) => `${value.replace("T", " ")}${value.length === 10 ? " 00:00:00" : value.length === 16 ? ":00" : ""}`;
const fromPickerValue = (value: string | null) => value ? value.slice(0, 16).replace(" ", "T") : "";

export default function ExpensesPage() {
  const expenses = useAdminStore((state) => state.expenses);
  const rules = useAdminStore((state) => state.autoExpenseRules);
  const save = useAdminStore((state) => state.saveExpense);
  const remove = useAdminStore((state) => state.deleteExpense);
  const [editing, setEditing] = useState<Expense | null | undefined>(undefined);
  const [selected, setSelected] = useState<Expense | null>(null);
  const [form, setForm] = useState<Expense>(blankExpense());
  const [category, setCategory] = useState("Semua jenis");
  const [status, setStatus] = useState("Semua status");
  const [startDate, setStartDate] = useState("2026-09-01");
  const [endDate, setEndDate] = useState("2026-09-30");
  const [sortBy, setSortBy] = useState("Tanggal terbaru");
  const [evidenceFile, setEvidenceFile] = useState<File | null>(null);
  const filtered = useMemo(() => expenses
    .filter((item) => (category === "Semua jenis" || item.category === category) && (status === "Semua status" || item.status === status) && item.date.slice(0, 10) >= startDate && item.date.slice(0, 10) <= endDate)
    .sort((a, b) => sortBy === "Tanggal terlama" ? a.date.localeCompare(b.date) : sortBy === "Nominal terbesar" ? b.amount - a.amount : sortBy === "Nominal terkecil" ? a.amount - b.amount : b.date.localeCompare(a.date)), [category, endDate, expenses, sortBy, startDate, status]);
  const done = filtered.filter((item) => item.status === "Done").reduce((sum, item) => sum + item.amount, 0);
  const pending = filtered.filter((item) => item.status === "Pending").reduce((sum, item) => sum + item.amount, 0);
  const maintenance = filtered.filter((item) => item.category === "Maintenance").reduce((sum, item) => sum + item.amount, 0);
  const open = (item?: Expense) => { setForm(item ? { ...item } : blankExpense()); setEvidenceFile(null); setEditing(item ?? null); };
  const update = <K extends keyof Expense>(key: K, value: Expense[K]) => setForm((current) => ({ ...current, [key]: value }));
  const updateStatus = (item: Expense, next: Expense["status"]) => { save({ ...item, status: next }); setSelected((current) => current?.id === item.id ? { ...current, status: next } : current); notifications.show({ color: next === "Done" ? "teal" : "yellow", message: `${item.reference} diubah menjadi ${next}.` }); };
  const submit = () => { if (!form.reference.trim() || !form.paidBy.trim() || form.amount <= 0 || (form.category === "Lainnya" && !form.customCategory?.trim())) { notifications.show({ color: "red", message: form.category === "Lainnya" && !form.customCategory?.trim() ? "Jenis pengeluaran lainnya wajib diisi." : "Referensi, sumber dana, dan nominal wajib diisi." }); return; } save({ ...form, customCategory: form.category === "Lainnya" ? form.customCategory?.trim() : "", evidenceUrl: evidenceFile ? evidenceFile.name : form.evidenceUrl }); setEditing(undefined); notifications.show({ color: "teal", message: "Pengeluaran berhasil disimpan." }); };
  const exportExpenses = () => exportCsv("pengeluaran-nao.csv", filtered.map((item) => ({ Referensi: item.reference, Tanggal: item.date, Jenis: expenseCategoryLabel(item), "Sumber dana": item.paidBy, Status: item.status, Nominal: item.amount, Catatan: item.notes, "Bukti transaksi": item.evidenceUrl })));

  const statusMenu = (item: Expense) => <Menu position="bottom-end" withinPortal><Menu.Target><UnstyledButton className="report-status-trigger" aria-label={`Ubah status ${item.reference}`}><Badge color={item.status === "Done" ? "teal" : "yellow"} variant="light" leftSection={<span className="status-dot" />} rightSection={<IconChevronDown size={12} />} className="report-status-badge">{item.status}</Badge></UnstyledButton></Menu.Target><Menu.Dropdown>{STATUS_OPTIONS.map((option) => <Menu.Item key={option} disabled={option === item.status} leftSection={<span className="status-option-dot" style={{ background: `var(--mantine-color-${option === "Done" ? "teal" : "yellow"}-6)` }} />} onClick={() => updateStatus(item, option)}>{option}</Menu.Item>)}</Menu.Dropdown></Menu>;

  return <><PageHeader eyebrow="Finance · Pengeluaran" title="Pengeluaran" description="Catat biaya operasional, reimbursement, maintenance, dan pengeluaran payroll." action={<Group><Button variant="light" color="dark" leftSection={<IconDownload size={16} />} onClick={exportExpenses}>Export CSV</Button><Button className="primary-action" leftSection={<IconPlus size={17} />} onClick={() => open()}>Tambah pengeluaran</Button></Group>} />
    <SimpleGrid cols={{ base: 1, xs: 2, xl: 4 }} mb="lg"><MetricCard label="Pengeluaran done" value={formatCurrency(done)} delta={`${filtered.filter((item) => item.status === "Done").length} transaksi`} icon={IconCheck} tone="green" /><MetricCard label="Menunggu pembayaran" value={formatCurrency(pending)} delta={`${filtered.filter((item) => item.status === "Pending").length} pending`} icon={IconWallet} tone="gold" /><MetricCard label="Maintenance" value={formatCurrency(maintenance)} delta="periode terpilih" icon={IconReceipt} tone="purple" /><MetricCard label="Aturan otomatis" value={String(rules.filter((item) => item.active).length)} delta="aktif setiap bulan" icon={IconBuildingBank} /></SimpleGrid>
    <Card className="recurring-banner" p="lg" mb="lg"><Group justify="space-between" align="center"><Group><Box className="recurring-icon"><IconBuildingBank size={18} /></Box><Box><Text fw={700}>Pengeluaran otomatis aktif</Text><Text size="xs" c="dimmed">{rules.filter((item) => item.active).map((item) => `${item.name} · tanggal ${item.dayOfMonth}`).join("; ") || "Belum ada aturan aktif."}</Text></Box></Group><Badge color="teal" variant="light">Recurring</Badge></Group></Card>
    <Card className="surface-card filter-card" p="lg" mb="lg"><Group align="flex-end" wrap="wrap"><Select label="Jenis pengeluaran" value={category} onChange={(value) => setCategory(value ?? "Semua jenis")} data={["Semua jenis", "Gaji", "Biaya admin bank", "Maintenance", "Lainnya"]} w={210} /><Select label="Status" value={status} onChange={(value) => setStatus(value ?? "Semua status")} data={["Semua status", "Pending", "Done"]} w={150} /><DatePickerInput type="range" label="Rentang tanggal" placeholder="Pilih tanggal mulai dan akhir" value={[startDate, endDate]} onChange={(value) => { setStartDate(value[0] ?? ""); setEndDate(value[1] ?? ""); }} valueFormat="DD MMM YYYY" clearable={false} w={250} /><Select label="Urutkan" value={sortBy} onChange={(value) => setSortBy(value ?? "Tanggal terbaru")} data={["Tanggal terbaru", "Tanggal terlama", "Nominal terbesar", "Nominal terkecil"]} w={190} /></Group></Card>
    <Card className="surface-card table-card" p={0}><Group p="lg" justify="space-between"><Box><Text className="section-title">Daftar pengeluaran</Text><Text size="xs" c="dimmed">{filtered.length} pencatatan · klik baris untuk melihat detail</Text></Box></Group><ScrollArea><Table miw={980} verticalSpacing="md" horizontalSpacing="lg" highlightOnHover><Table.Thead><Table.Tr><Table.Th>Referensi</Table.Th><Table.Th>Jenis</Table.Th><Table.Th>Sumber dana</Table.Th><Table.Th>Catatan</Table.Th><Table.Th>Status</Table.Th><Table.Th ta="right">Nominal</Table.Th><Table.Th /></Table.Tr></Table.Thead><Table.Tbody>{filtered.map((item) => <Table.Tr key={item.id} className="clickable-row" tabIndex={0} onClick={() => setSelected(item)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") setSelected(item); }}><Table.Td><Text size="xs" ff="monospace" fw={600}>{item.reference}</Text><Text size="xs" c="dimmed">{formatDate(item.date)}</Text></Table.Td><Table.Td><Group gap={6}><Badge variant="outline" color={item.category === "Gaji" ? "dark" : item.category === "Maintenance" ? "violet" : "yellow"}>{expenseCategoryLabel(item)}</Badge>{item.recurring && <Badge size="xs" color="teal" variant="light">Auto</Badge>}</Group></Table.Td><Table.Td><Text size="sm" fw={600}>{item.paidBy}</Text></Table.Td><Table.Td><Text size="xs" c="dimmed" maw={280} lineClamp={2}>{item.notes}</Text></Table.Td><Table.Td onClick={(event) => event.stopPropagation()}>{statusMenu(item)}</Table.Td><Table.Td ta="right" fw={700}>{formatCurrency(item.amount)}</Table.Td><Table.Td onClick={(event) => event.stopPropagation()}><Menu position="bottom-end"><Menu.Target><ActionIcon variant="subtle" color="gray" aria-label={`Aksi ${item.reference}`}><IconDotsVertical size={17} /></ActionIcon></Menu.Target><Menu.Dropdown>{item.evidenceUrl && <Menu.Item leftSection={<IconExternalLink size={15} />}>Lihat bukti transaksi</Menu.Item>}<Menu.Item leftSection={<IconEdit size={15} />} onClick={() => open(item)}>Edit</Menu.Item><Menu.Item color="red" leftSection={<IconTrash size={15} />} onClick={() => { if (window.confirm("Hapus pengeluaran ini?")) remove(item.id); }}>Hapus</Menu.Item></Menu.Dropdown></Menu></Table.Td></Table.Tr>)}</Table.Tbody></Table></ScrollArea></Card>
    <Drawer opened={Boolean(selected)} onClose={() => setSelected(null)} position="right" size="md" title={<Text className="section-title">Detail pengeluaran</Text>}>{selected && <Stack gap="lg"><Card className="detail-hero" p="lg"><Group justify="space-between" align="flex-start"><Box><Text ff="monospace" fw={700}>{selected.reference}</Text><Text size="sm" c="dimmed" mt={4}>{formatDate(selected.date)}</Text></Box>{statusMenu(selected)}</Group><Text className="payment-detail-value">{formatCurrency(selected.amount)}</Text></Card><SimpleGrid cols={2}><DetailItem label="Jenis" value={expenseCategoryLabel(selected)} /><DetailItem label="Sumber dana" value={selected.paidBy} /><DetailItem label="Dibuat otomatis" value={selected.recurring ? "Ya" : "Tidak"} /><DetailItem label="Bukti transaksi" value={selected.evidenceUrl || "Belum ada"} /></SimpleGrid><Divider /><Box><Text className="section-title" mb="sm">Catatan</Text><Text size="sm" c="dimmed" lh={1.7}>{selected.notes || "Tidak ada catatan tambahan."}</Text></Box><Button variant="light" color="dark" leftSection={<IconEdit size={16} />} onClick={() => { open(selected); setSelected(null); }}>Edit pengeluaran</Button></Stack>}</Drawer>
    <Modal opened={editing !== undefined} onClose={() => setEditing(undefined)} size="lg" centered title={<Text className="section-title">{editing ? "Edit pengeluaran" : "Tambah pengeluaran"}</Text>}><Stack><SimpleGrid cols={{ base: 1, sm: 2 }}><Select label="Jenis pengeluaran" required value={form.category} onChange={(value) => update("category", (value ?? "Lainnya") as Expense["category"])} data={["Gaji", "Biaya admin bank", "Maintenance", "Lainnya"]} />{form.category === "Lainnya" && <TextInput label="Jenis pengeluaran lainnya" placeholder="Contoh: Transportasi" required value={form.customCategory ?? ""} onChange={(event) => update("customCategory", event.currentTarget.value)} />}<Select label="Status" required value={form.status} onChange={(value) => update("status", (value ?? "Pending") as Expense["status"])} data={STATUS_OPTIONS} /><TextInput label="Referensi" required value={form.reference} onChange={(event) => update("reference", event.currentTarget.value)} /><DateTimePicker label="Tanggal dan waktu" placeholder="Pilih tanggal dan waktu" required value={toPickerValue(form.date)} onChange={(value) => update("date", fromPickerValue(value))} valueFormat="DD MMMM YYYY, HH:mm" clearable={false} timePickerProps={{ format: "24h" }} /><TextInput label="Sumber dana" required value={form.paidBy} onChange={(event) => update("paidBy", event.currentTarget.value)} /><NumberInput label="Nominal" required min={0} value={form.amount} onChange={(value) => update("amount", Number(value) || 0)} prefix="Rp " thousandSeparator="." decimalSeparator="," /></SimpleGrid><SimpleGrid cols={{ base: 1, sm: 2 }}><TextInput label="Link bukti transaksi" placeholder="https://drive.google.com/..." value={form.evidenceUrl} onChange={(event) => update("evidenceUrl", event.currentTarget.value)} /><FileInput label="Atau upload bukti" placeholder="PDF/JPG/PNG" accept="application/pdf,image/png,image/jpeg" value={evidenceFile} onChange={setEvidenceFile} leftSection={<IconUpload size={16} />} /></SimpleGrid><Textarea label="Catatan" minRows={3} value={form.notes} onChange={(event) => update("notes", event.currentTarget.value)} /><Group justify="flex-end"><Button variant="subtle" color="gray" onClick={() => setEditing(undefined)}>Batal</Button><Button className="primary-action" leftSection={<IconCheck size={16} />} onClick={submit}>Simpan pengeluaran</Button></Group></Stack></Modal>
  </>;
}
